/*
!!!SCRIPT IS WIP!!!
autohotkey script to automate dynamx to excel conversion, current dynamx application does not
support the exporting of data to excel for bimodal analysis


Prerequisites before starting: 
	- must have DynamX open with file of interest opened
	- DynamX window must be maximized
	- user must be present

Goal:
	- user click on sequence then presses hotkey 
		- hotkey automates clicking on -->views-->stacked spectral plot-->click on desired spectrum-->copy spectrum --> open excel-->paste spectrum
      	
        -test for compatibilty with hx express
		-test excel file generated by ahk can be accepted by hx express

		- could possibly implement a excel data format option for bimodal analysis
			-same script or create a different script
				ie. powershell 
	- gradually automate user clicking process




ctrl M: starts the script 

For window spy for AHKv2:
-  window size=screen size
*/



#HotIf WinExist("ahk_class LVDChild")
^m::
{

WinActivate "ahk_class LVDChild"
WinMaximize


WinGetPos ,, &w, &h, "A"

;Mousex := 0.06*w
;Mousey := 0.01*h

MouseMove 100,9,0

;MsgBox "mouse coord=" Mousex " , " Mousey
;MsgBox "Success"
}


;turn off script option 
~Escape::ExitApp
